    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                    </a> <br>
                    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal">
                    <div class="form-group">
                      <label for="username" class="col-sm-2 control-label">Username</label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" id="username" placeholder="Digite Seu Nome de Usuario Aqui ...">
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="password" class="col-sm-2 control-label">Senha</label>
                      <div class="col-sm-10">
                        <input type="password" class="form-control" id="Password" placeholder="Digite Sua Senha Aqui ...">
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="col-sm-offset-2 col-sm-10">
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success pull-right">Login</button>
                      </div>
                    </div>
                  </form>
                </div>
            </div>
        </div>
    </div>
